### ISSUE TITLE
Error: Invalid file 'workflows.json' on using the content.zip

### ISSUE THREAD

**Issue by sangramrath** [alanta/Memoirs-Theme#4]
Hello @alanta,

Is it possible to get an updated content.zip file that has the workflow.json and some others that are missing. On using this content.zip with the Kontent.ai Backup Manager which is now **@kontent-ai/backup-manager** it complains of invalid file error. I have attached a screenshot.

Thank You for your time. 

![Screenshot 2023-12-06 at 8 06 07 PM](https://github.com/alanta/memoirs-theme/assets/6134395/1971e665-8311-4238-b4da-4910b55d02fc)

**Comment by alanta** [comment]
I'll see what I can do. It's been a while...

**Comment by alanta** [comment]
@sangramrath can you take a look at PR #5  and let me know if the new content.zip file works for you?

**Comment by sangramrath** [comment]
Hello @alanta. I was travelling and haven't been able to check notifications. 
Thank You for the new zip, allow me a couple of days to update you on this.
